const fs = require('fs');
const path = require('path');

const EXCLUDED_DIRS = ['.git', 'node_modules', '.gemini', 'brain', 'scratch', 'dist', '.github'];

function scanDir() {
  const rootDir = __dirname;
  const result = {};

  const items = fs.readdirSync(rootDir);
  for (const item of items) {
    const itemPath = path.join(rootDir, item);
    const stat = fs.statSync(itemPath);

    if (stat.isDirectory()) {
      if (EXCLUDED_DIRS.includes(item)) continue;

      // Scan for markdown files inside this directory
      const files = fs.readdirSync(itemPath);
      const mdFiles = files.filter(f => {
        const ext = path.extname(f).toLowerCase();
        return (ext === '.md' || ext === '.markdown') && fs.statSync(path.join(itemPath, f)).isFile();
      });

      if (mdFiles.length > 0) {
        // Sort files alphabetically (natural sort)
        mdFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
        result[item] = mdFiles;
      }
    }
  }

  const outputContent = `// Automatically generated by generate-list.js\nwindow.MARKMAP_FILES = ${JSON.stringify(result, null, 2)};\n`;
  fs.writeFileSync(path.join(rootDir, 'files-data.js'), outputContent, 'utf-8');
  console.log('Successfully generated files-data.js with folders:', Object.keys(result));
}

scanDir();
